name: Run tests

on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  test-convertanything:
    uses: ./.github/workflows/operation-test-with-jupyter.yml
    with:
      notebook: tests/tests.ipynb
      image: joshxt/ezlocalai:main
      port: "8091"
      additional-python-dependencies: requests pydantic
      clone-repo: true
