name: Run tests

on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  test-convertanything:
    uses: ./.github/workflows/test-with-ezlocalai.yml
    with:
      additional-python-dependencies: pydantic
      clone-repo: true
